version: '3.10'
services:
  tg_bitrix:
    container_name: tg_bitrix_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
      - migrations
    restart: always

  db:
    container_name: tg_bitrix_db
    image: postgres:14.3
    ports:
      - "5437:5437"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "port=5437"
    restart: always

  migrations:
    container_name: tg_bitrix_migrations
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5437; do sleep 1; done; alembic upgrade head'
    restart: "no"
    environment:
      env_file: .env
    depends_on:
      - db
